---
# defaults file for galaxyproject.nginx

- name: Test nginx configuration
  command: nginx -t
  listen:
    - reload nginx
    - restart nginx

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
