---
# defaults file for galaxyproject.nginx

- name: test nginx configuration
  command: nginx -t
  listen:
    - reload nginx
    - restart nginx
  when: not nginx_supervisor

- name: test nginx configuration (supervisor)
  command: nginx -t
  listen:
    - supervisorctl reload nginx
    - supervisorctl restart nginx
  when: nginx_supervisor and supervisord_prefix is defined

- name: reload nginx
  service:
    name: nginx
    state: reloaded
  when: not nginx_supervisor

- name: restart nginx
  service:
    name: nginx
    state: restarted
  when: not nginx_supervisor

- name: supervisorctl reload nginx
  # TODO: do this better
  command: pkill -HUP nginx
  when: nginx_supervisor and supervisord_prefix is defined

- name: supervisorctl restart nginx
  supervisorctl:
    config: "{{ supervisord_conf_path }}"
    name: "{{ nginx_supervisor_service_name }}"
    supervisorctl_path: "{{ supervisord_prefix ~ '/bin/supervisorctl' }}"
    state: restarted
  when: nginx_supervisor and supervisord_prefix is defined
